/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    
	public int  somme(int a, int b) {
		return a+b;
	}
	public int  soustraction(int a, int b) {
		return a-b;
	}
}
